### PR TITLE
Make pool compatible with dbplyr

### LINKED ISSUE #39: Make compatible with dbplyr
1.  The implementation of the dplyr database backends has moved to dbplyr. Most of the generics remain in dplyr, so that existing backends don't break.

2. By inspecting the namespace, you can now easily see what methods you need to override for non-DBIConnections. Here's the complete list

````
 db_analyze
 db_begin
 db_collect
 db_commit
 db_compute
 db_copy_to
 db_create_index
 db_create_indexes
 db_create_table
 db_data_type
 db_desc
 db_drop_table
 db_explain
 db_has_table
 db_insert_into
 db_list_tables
 db_query_fields
 db_query_rows
 db_rollback
 db_save_query
 db_sql_render
 db_write_table
 sql_escape_ident
 sql_escape_string
 sql_join
 sql_select
 sql_semi_join
 sql_subquery
 sql_translate_env
 ````

3.  There are a lot of methods, but most of them simply require you to acquire the connection, then release it when it's done. To make that easier, I've written you this function to generate the wrapper functions:

``` r
 library(dplyr, warn.conflicts = FALSE)
 library(rlang)

pool_wrap <- function(f) {
 f <- enquo(f)

formals <- formals(eval_tidy(f))
 con <- names(formals)[[1]]
 passed_on <- names(formals[-1]) %>%
 set_names() %>% 
 lapply(as_symbol)

body <- expr({
 db_con <- poolCheckout(!!sym(con))
 on.exit(poolReturn(db_con))

UQE(f)(db_con, !!!passed_on)
 })

new_function(formals, body, f_env(f))
 }

pool_wrap(db_analyze)
 #> function (con, table, ...) 
 #> {
 #>     db_con <- poolCheckout(con)
 #>     on.exit(poolReturn(db_con))
 #>     db_analyze(db_con, table = table, ... = ...)
 #> }
 #> <environment: 0x7ff69c8927c8>
 ```

4.  There are at least two exceptions: `copy_to()` and `compute()` will need need to throw an error if `temporary = TRUE` because temporary tables are local to a connection, and there's no guarantee you'll get the same connection back next time.

I'm reasonably certain I've made all the changes to dbplyr to facilitate your Pool, but please let me know if I've missed anything. I'm also happy to hop on a call with you and @jcheng5 to answer any questions that you might have.

### PR DESCRIPTION
**Pull request by bborgesr**
Fixes #39

```r
# install.packages("nycflights13")
# install.packages("dplyr")
# devtools::install_github("rstudio/pool@fix/dbplyr")

library(dplyr)
library(pool)

# Using dbplyr directly

# con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory:")
# 
# copy_to(con, nycflights13::flights, "flights",
#   temporary = FALSE, 
#   indexes = list(
#     c("year", "month", "day"), 
#     "carrier", 
#     "tailnum",
#     "dest"
#   )
# )
# 
# (flights_db <- tbl(con, "flights"))
# 
# flights_db %>% select(year:day, dep_delay, arr_delay)
# flights_db %>% filter(dep_delay > 240)
# flights_db %>% 
#   group_by(dest) %>%
#   summarise(delay = mean(dep_time))
# 
# tailnum_delay_db <- flights_db %>% 
#   group_by(tailnum) %>%
#   summarise(
#     delay = mean(arr_delay),
#     n = n()
#   ) %>% 
#   arrange(desc(delay)) %>%
#   filter(n > 100)
# 
# tailnum_delay_db


# Using pool
pool <- dbPool(RSQLite::SQLite(), path = ":memory:")

copy_to(pool, nycflights13::flights, "flights",
  temporary = FALSE, 
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)

(flights_db <- tbl(pool, "flights"))

flights_db %>% select(year:day, dep_delay, arr_delay)
flights_db %>% filter(dep_delay > 240)
flights_db %>% 
  group_by(dest) %>%
  summarise(delay = mean(dep_time))

tailnum_delay_db <- flights_db %>% 
  group_by(tailnum) %>%
  summarise(
    delay = mean(arr_delay),
    n = n()
  ) %>% 
  arrange(desc(delay)) %>%
  filter(n > 100)

tailnum_delay_db

poolClose(pool)
```

### CODE REVIEW

File: R/dbplyr.R [hunk 1]
```diff
@@ -0,0 +1,282 @@
+#' @include DBI.R
+NULL
+
+temporaryErrorMessage <- paste0("You cannot use `temporary = TRUE`",
```
Comment (hadley) [inline R/dbplyr.R]: I think this would be slightly better as `checkTemporary()`, i.e. including the boilerplate `if (temporary) stop(temporaryErrorMessage)`

File: R/dbplyr.R [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+db_create_indexes.Pool <- function(con, table, indexes = NULL,
+  unique = FALSE, ...) {
+    db_con <- poolCheckout(con)
+    on.exit(poolReturn(db_con))
+    db_create_indexes(db_con, table = table, indexes = indexes,
+      unique = unique, ... = ...)
+}
+
+#' @export
+db_create_table.Pool <- function(con, table, types, temporary = FALSE, ...) {
```
Comment (hadley) [inline R/dbplyr.R]: I do wonder about changing the default value of `temporary` here. Obviously it's going to be annoying if it's `TRUE`, but it might be surprising if it's `FALSE`.

File: R/dbplyr.R [hunk 3]
```diff
@@ -0,0 +1,282 @@
...
+  "connection back next time. You must either create a permanent ",
+  "table, or checkout a connection from `pool` directly with ",
+  "`con <- poolCheckout(pool)`, and then release the connection ",
+  "back to the pool when you're finished (`poolReturn(con)`).")
+
+# --- These generics are set in dplyr (not database-specific)
+#' @export
+copy_to.Pool <- function(dest, df, name = deparse(substitute(df)),
+  overwrite = FALSE, ...) {
+    db_con <- poolCheckout(dest)
```
Comment (hadley) [inline R/dbplyr.R]: I now know how to convert 

```R
db_con <- poolCheckout(dest)
on.exit(poolReturn(db_con))
```

to 

```R
db_con <- localPoolCheckout(dest)
```

with the `on.exit()` being automatically added. 

It's up to you if you'd prefer that API.

Comment (jcheng5) [inline R/dbplyr.R]: I find that slightly terrifying

File: R/dbplyr.R (hunk 2 above)
Comment (jcheng5) [inline R/dbplyr.R]: Isn't the default always `FALSE`? Are you wondering about changing the default in dplyr itself?

File: R/dbplyr.R (hunk 1 above)
Comment (jcheng5) [inline R/dbplyr.R]: @hadley What do you think of long, narrative error messages like this?

File: R/dbplyr.R (hunk 2 above)
Comment (bborgesr) [inline R/dbplyr.R]: You mean changing it in the original generic in `dplyr`? Or just here in `pool`?

Comment (bborgesr) [inline R/dbplyr.R]: (sorry Joe, didn't see your comment asking exactly the same thing)

File: R/dbplyr.R (hunk 3 above)
Comment (bborgesr) [inline R/dbplyr.R]: If it's quick to explain, can you elaborate on why, @jcheng5? Also, @hadley, this is merely in your head now, right? (I couldn't find any instances of `localPoolCheckout`in github)

File: R/dbplyr.R (hunk 2 above)
Comment (hadley) [inline R/dbplyr.R]: Isn't the default in the generic `TRUE`?

File: R/dbplyr.R (hunk 1 above)
Comment (hadley) [inline R/dbplyr.R]: I have mixed feelings. They feel inelegant to me, but users tend to really appreciate them.

File: R/dbplyr.R (hunk 2 above)
Comment (bborgesr) [inline R/dbplyr.R]: @hadley No: https://github.com/tidyverse/dplyr/blob/master/R/dbplyr.R#L95 Or am I missing something?

**Comment by bborgesr** [comment]
@hadley, is there anything that you think I may have missed? All I did was a thin Pool wrapper around all the methods for DBIConnection (including `copy_to()` and `tbl()`), and throw an error when `temporary = TRUE`. Is this enough? In particular, I was wondering about your 3rd item from [here](https://github.com/tidyverse/dplyr/issues/2479):
> Rework joins so that upload happens later, using same connection as the rest of the query

File: R/dbplyr.R [hunk 4]
```diff
@@ -0,0 +1,274 @@
...
+  paste0(sample(letters, n, replace = TRUE), collapse = "")
+}
+
+#' @export
+sql_subquery.Pool <- function(con, from,
+  name = random_table_name(), ...) {
+    db_con <- poolCheckout(con)
+    on.exit(poolReturn(db_con))
+    sql_subquery(db_con, from = from, name = name, ... = ...)
+}
```
Comment (bborgesr) [inline R/dbplyr.R]: another worry I have is if this function is amenable to `pool`. Is the `name = random_table_name()`'s value actually made into a table using `create_table` or something?

File: R/dbplyr.R (hunk 2 above)
Comment (hadley) [inline R/dbplyr.R]: Ok, I was confused. You can ignore this whole thread.

File: R/dbplyr.R (hunk 4 above)
Comment (hadley) [inline R/dbplyr.R]: No, it's for databases that require subqueries be named (even if that name isn't actually used for anything).
